import { Product, ProductCategory, MetalType } from './types'

export const mockProducts: Product[] = [
  // Alianças de Casamento
  {
    id: '1',
    name: 'Aliança Tradicional Lisa',
    slug: 'alianca-tradicional-lisa',
    description: 'Aliança de casamento em ouro 18k, acabamento liso e polido. Design clássico e atemporal, perfeito para simbolizar seu amor eterno.',
    price: 2340.00,
    images: ['/products/alianca-lisa-amarela.svg'],
    category: ProductCategory.ALIANCAS_CASAMENTO,
    metalType: MetalType.OURO_18K_AMARELO,
    collection: 'Clássica',
    weight: 8.5,
    width: 4.0,
    thickness: 1.5,
    inStock: true,
    featured: true,
    specifications: [
      'Ouro 18k (750)',
      'Acabamento polido',
      'Largura: 4mm',
      'Espessura: 1.5mm',
      'Peso aproximado: 8.5g (par)',
    ],
    customizable: true,
  },
  {
    id: '2',
    name: 'Aliança Anatômica com Friso',
    slug: 'alianca-anatomica-com-friso',
    description: 'Aliança anatômica em ouro 18k branco, com friso central em ouro amarelo. Conforto absoluto e design sofisticado.',
    price: 3890.00,
    images: ['/products/alianca-anatomica-branca.svg'],
    category: ProductCategory.ALIANCAS_CASAMENTO,
    metalType: MetalType.OURO_18K_BRANCO,
    collection: 'Anatômica',
    weight: 10.2,
    width: 5.0,
    thickness: 1.8,
    inStock: true,
    featured: true,
    specifications: [
      'Ouro 18k branco (750)',
      'Friso em ouro amarelo',
      'Design anatômico',
      'Largura: 5mm',
      'Espessura: 1.8mm',
      'Peso aproximado: 10.2g (par)',
    ],
    customizable: true,
  },
  {
    id: '3',
    name: 'Aliança Trabalhada Diamantada',
    slug: 'alianca-trabalhada-diamantada',
    description: 'Aliança em ouro 18k amarelo com acabamento diamantado. Brilho e elegância para marcar sua união.',
    price: 4250.00,
    images: ['/products/alianca-diamantada-amarela.svg'],
    category: ProductCategory.ALIANCAS_CASAMENTO,
    metalType: MetalType.OURO_18K_AMARELO,
    collection: 'Trabalhada',
    weight: 9.8,
    width: 4.5,
    thickness: 1.6,
    inStock: true,
    specifications: [
      'Ouro 18k amarelo (750)',
      'Acabamento diamantado',
      'Largura: 4.5mm',
      'Espessura: 1.6mm',
      'Peso aproximado: 9.8g (par)',
    ],
    customizable: true,
  },
  {
    id: '4',
    name: 'Aliança Rose Gold Moderna',
    slug: 'alianca-rose-gold-moderna',
    description: 'Aliança em ouro 18k rosé, com design moderno e romântico. Tendência e sofisticação em uma peça única.',
    price: 4680.00,
    images: ['/products/alianca-rose-moderna.svg'],
    category: ProductCategory.ALIANCAS_CASAMENTO,
    metalType: MetalType.OURO_18K_ROSE,
    collection: 'Moderna',
    weight: 11.5,
    width: 5.5,
    thickness: 1.9,
    inStock: true,
    featured: true,
    specifications: [
      'Ouro 18k rosé (750)',
      'Design moderno',
      'Acabamento polido',
      'Largura: 5.5mm',
      'Espessura: 1.9mm',
      'Peso aproximado: 11.5g (par)',
    ],
    customizable: true,
  },
  {
    id: '5',
    name: 'Aliança Bicolor Premium',
    slug: 'alianca-bicolor-premium',
    description: 'Aliança premium em ouro 18k bicolor (branco e amarelo). Sofisticação máxima com design exclusivo.',
    price: 5890.00,
    images: ['/products/alianca-bicolor-premium.svg'],
    category: ProductCategory.ALIANCAS_CASAMENTO,
    metalType: MetalType.OURO_18K_BRANCO,
    collection: 'Premium',
    weight: 13.2,
    width: 6.0,
    thickness: 2.0,
    inStock: true,
    featured: true,
    specifications: [
      'Ouro 18k bicolor (750)',
      'Combinação branco e amarelo',
      'Design exclusivo',
      'Largura: 6mm',
      'Espessura: 2mm',
      'Peso aproximado: 13.2g (par)',
    ],
    customizable: true,
  },

  // Alianças de Noivado
  {
    id: '6',
    name: 'Aliança de Noivado Delicada',
    slug: 'alianca-noivado-delicada',
    description: 'Aliança de noivado em ouro 18k amarelo, design delicado e fino. Perfeita para marcar o início de uma nova jornada.',
    price: 1890.00,
    images: ['/products/alianca-noivado-delicada.svg'],
    category: ProductCategory.ALIANCAS_NOIVADO,
    metalType: MetalType.OURO_18K_AMARELO,
    collection: 'Delicada',
    weight: 4.5,
    width: 3.0,
    thickness: 1.2,
    inStock: true,
    specifications: [
      'Ouro 18k amarelo (750)',
      'Design delicado',
      'Largura: 3mm',
      'Espessura: 1.2mm',
      'Peso aproximado: 4.5g (par)',
    ],
    customizable: true,
  },

  // Anéis
  {
    id: '7',
    name: 'Anel Solitário Clássico',
    slug: 'anel-solitario-classico',
    description: 'Anel solitário em ouro 18k amarelo com design clássico. Elegância pura em uma peça atemporal.',
    price: 3200.00,
    images: ['/products/anel-solitario-amarelo.svg'],
    category: ProductCategory.ANEIS,
    metalType: MetalType.OURO_18K_AMARELO,
    collection: 'Solitário',
    weight: 6.5,
    inStock: true,
    specifications: [
      'Ouro 18k amarelo (750)',
      'Design solitário',
      'Acabamento polido',
      'Peso aproximado: 6.5g',
    ],
    customizable: false,
  },
  {
    id: '8',
    name: 'Anel Aparador Sofisticado',
    slug: 'anel-aparador-sofisticado',
    description: 'Anel aparador em ouro 18k branco, design sofisticado para complementar sua aliança.',
    price: 2680.00,
    images: ['/products/anel-aparador-branco.svg'],
    category: ProductCategory.ANEIS,
    metalType: MetalType.OURO_18K_BRANCO,
    weight: 5.8,
    inStock: true,
    specifications: [
      'Ouro 18k branco (750)',
      'Design complementar',
      'Acabamento polido',
      'Peso aproximado: 5.8g',
    ],
    customizable: false,
  },

  // Anéis de Formatura
  {
    id: '9',
    name: 'Anel de Formatura Direito',
    slug: 'anel-formatura-direito',
    description: 'Anel de formatura em ouro 18k amarelo, design tradicional. Personalize com o símbolo do seu curso e pedra de sua escolha.',
    price: 4500.00,
    images: ['/products/anel-formatura-direito.svg'],
    category: ProductCategory.ANEIS_FORMATURA,
    metalType: MetalType.OURO_18K_AMARELO,
    collection: 'Formatura Direito',
    weight: 15.0,
    inStock: true,
    featured: true,
    specifications: [
      'Ouro 18k amarelo (750)',
      'Design tradicional',
      'Personalizável com símbolo do curso',
      'Opções de pedras',
      'Peso aproximado: 15g',
    ],
    customizable: true,
  },
  {
    id: '10',
    name: 'Anel de Formatura Medicina',
    slug: 'anel-formatura-medicina',
    description: 'Anel de formatura em ouro 18k branco para Medicina. Design exclusivo com o símbolo do caduceu.',
    price: 5200.00,
    images: ['/products/anel-formatura-medicina.svg'],
    category: ProductCategory.ANEIS_FORMATURA,
    metalType: MetalType.OURO_18K_BRANCO,
    collection: 'Formatura Medicina',
    weight: 16.5,
    inStock: true,
    featured: true,
    specifications: [
      'Ouro 18k branco (750)',
      'Símbolo do caduceu',
      'Design exclusivo para Medicina',
      'Personalizável',
      'Peso aproximado: 16.5g',
    ],
    customizable: true,
  },
  {
    id: '11',
    name: 'Anel de Formatura Engenharia',
    slug: 'anel-formatura-engenharia',
    description: 'Anel de formatura em ouro 18k amarelo para Engenharia. Robusto e elegante, com símbolo da profissão.',
    price: 4890.00,
    images: ['/products/anel-formatura-engenharia.svg'],
    category: ProductCategory.ANEIS_FORMATURA,
    metalType: MetalType.OURO_18K_AMARELO,
    collection: 'Formatura Engenharia',
    weight: 17.2,
    inStock: true,
    specifications: [
      'Ouro 18k amarelo (750)',
      'Símbolo da Engenharia',
      'Design robusto',
      'Personalizável',
      'Peso aproximado: 17.2g',
    ],
    customizable: true,
  },
  {
    id: '12',
    name: 'Anel de Formatura Administração',
    slug: 'anel-formatura-administracao',
    description: 'Anel de formatura em ouro 18k rosé para Administração. Moderno e sofisticado.',
    price: 4650.00,
    images: ['/products/anel-formatura-adm.svg'],
    category: ProductCategory.ANEIS_FORMATURA,
    metalType: MetalType.OURO_18K_ROSE,
    collection: 'Formatura Administração',
    weight: 15.8,
    inStock: true,
    specifications: [
      'Ouro 18k rosé (750)',
      'Símbolo da Administração',
      'Design moderno',
      'Personalizável',
      'Peso aproximado: 15.8g',
    ],
    customizable: true,
  },

  // Mais alianças premium
  {
    id: '13',
    name: 'Aliança Exclusiva Texturizada',
    slug: 'alianca-exclusiva-texturizada',
    description: 'Aliança exclusiva em ouro 18k com textura especial. Design único e personalizado para casais que buscam originalidade.',
    price: 7200.00,
    images: ['/products/alianca-texturizada-exclusiva.svg'],
    category: ProductCategory.ALIANCAS_CASAMENTO,
    metalType: MetalType.OURO_18K_AMARELO,
    collection: 'Exclusiva',
    weight: 14.8,
    width: 6.5,
    thickness: 2.2,
    inStock: true,
    featured: true,
    specifications: [
      'Ouro 18k amarelo (750)',
      'Textura exclusiva',
      'Design personalizado',
      'Largura: 6.5mm',
      'Espessura: 2.2mm',
      'Peso aproximado: 14.8g (par)',
    ],
    customizable: true,
  },
  {
    id: '14',
    name: 'Aliança Imperial',
    slug: 'alianca-imperial',
    description: 'Aliança imperial em ouro 18k branco, com largura especial. Máxima elegância e presença para o dia mais especial.',
    price: 9070.00,
    images: ['/products/alianca-imperial-branca.svg'],
    category: ProductCategory.ALIANCAS_CASAMENTO,
    metalType: MetalType.OURO_18K_BRANCO,
    collection: 'Imperial',
    weight: 18.5,
    width: 8.0,
    thickness: 2.5,
    inStock: true,
    featured: true,
    discount: 10,
    specifications: [
      'Ouro 18k branco (750)',
      'Largura especial: 8mm',
      'Design imperial',
      'Acabamento premium',
      'Espessura: 2.5mm',
      'Peso aproximado: 18.5g (par)',
    ],
    customizable: true,
  },
]

// Collections for filtering
export const collections = [
  'Clássica',
  'Anatômica',
  'Trabalhada',
  'Moderna',
  'Premium',
  'Delicada',
  'Exclusiva',
  'Imperial',
  'Solitário',
  'Formatura Direito',
  'Formatura Medicina',
  'Formatura Engenharia',
  'Formatura Administração',
]

// Helper functions
export function getProductsByCategory(category: ProductCategory): Product[] {
  return mockProducts.filter(p => p.category === category)
}

export function getProductsByMetalType(metalType: MetalType): Product[] {
  return mockProducts.filter(p => p.metalType === metalType)
}

export function getProductsByCollection(collection: string): Product[] {
  return mockProducts.filter(p => p.collection === collection)
}

export function getFeaturedProducts(): Product[] {
  return mockProducts.filter(p => p.featured)
}

export function getProductBySlug(slug: string): Product | undefined {
  return mockProducts.find(p => p.slug === slug)
}
